### ISSUE TITLE
Updated Version

### ISSUE THREAD

**Issue by kscott-1** [hihg-um/docker-analytics#1]
Is this the most updated build? Running 'make' on this repo only echoes the container names, but doesn't do any building.

**Comment by thebigcorporation** [comment]
Try make docker and I’ll check for a missing push asapSent from my iPhoneOn Apr 24, 2023, at 06:17, Kyle Scott ***@***.***> wrote:﻿
Is this the most updated build? Running 'make' on this repo only echoes the container names, but doesn't do any building.

**Comment by kscott-1** [comment]
make docker solved the issue, container is building.

**Comment by thebigcorporation** [comment]
I think we also want to run make docker_test afterwards; this could be done in 2 stages ideally, or simply make docker docker_test

**Comment by thebigcorporation** [comment]
I think the default target was intended to run make help.
I have seen that for huge builds, where e.g. you may not even want to run apptainer anything, but let me look at how kernel.org handles it these days

**Comment by thebigcorporation** [comment]
I see it also printing the list of possible targets.

$ make
Targets: all build clean test release
         docker docker_base docker_clean docker_test docker_release
         apptainer apptainer_clean apptainer_realclean apptainer_test

Docker container(s):
	bcftools:v0.2.2-0-g6e5c88c-dirty_x86_64_linux
...
Apptainer(s):
	bcftools_v0.2.2-0-g6e5c88c-dirty_x86_64_linux.sif
...

In regards to build and test targets, if we want those combined, it would be easy to add another target depending on both build and test.
